"""
Sound to Painting
------------------
Converts a .wav audio file into an image, using the reverse of the
painting_to_sound.py logic.

How it works:
- The audio is split into small time-slices (left to right = time,
  same as scanning a painting column by column).
- Each time-slice is analyzed with an FFT to find which frequencies
  are present and how strong they are.
- For each slice:
    - The frequencies are grouped into "rows" (top = high pitch,
      bottom = low pitch), mirroring how painting_to_sound.py mapped
      row position -> pitch.
    - The dominant frequency in that slice determines the hue (color).
    - The overall loudness of the slice determines brightness.
- The result is a grid of colored pixels that get resized/smoothed
  into a final image.

This is NOT a perfect inverse (audio -> image is a lossy, creative
mapping, not a literal undo), but for audio that was generated by
painting_to_sound.py, you'll get back something visually related to
the original painting's color palette and structure.

Usage:
    python sound_to_painting.py <path_to_wav> [output.png] [width] [height]

Example:
    python sound_to_painting.py output.wav recovered.png 120 40
"""

import sys
import colorsys
import numpy as np
from scipy.io.wavfile import read
from PIL import Image


def frequency_to_hue(freq, low=110, high=880):
    """Inverse of hue_to_frequency() in painting_to_sound.py."""
    freq = np.clip(freq, low, high)
    hue = np.log(freq / low) / np.log(high / low)
    return np.clip(hue, 0, 1)


def load_audio(path):
    sample_rate, data = read(path)
    # If stereo, collapse to mono by averaging channels
    if data.ndim > 1:
        data = data.mean(axis=1)
    # Normalize to -1..1 float
    data = data.astype(np.float32)
    data /= np.max(np.abs(data)) + 1e-9
    return sample_rate, data


def sound_to_painting(audio_path, output_path="recovered.png", width=120, height=40):
    sample_rate, audio = load_audio(audio_path)

    total_samples = len(audio)
    samples_per_col = total_samples // width

    img = np.zeros((height, width, 3), dtype=np.uint8)

    # Frequency bins we care about, spread low -> high like painting rows
    # (top row = high pitch, bottom row = low pitch, matching original mapping)
    freq_low, freq_high = 60, 1200

    for col in range(width):
        start = col * samples_per_col
        end = start + samples_per_col
        chunk = audio[start:end]
        if len(chunk) == 0:
            continue

        # Windowing reduces spectral leakage for a cleaner FFT
        windowed = chunk * np.hanning(len(chunk))
        spectrum = np.abs(np.fft.rfft(windowed))
        freqs = np.fft.rfftfreq(len(windowed), d=1 / sample_rate)

        # Overall loudness of this slice -> brightness
        loudness = np.sqrt(np.mean(chunk ** 2))

        # Dominant frequency in this slice -> hue
        if spectrum.max() > 0:
            dominant_freq = freqs[np.argmax(spectrum)]
        else:
            dominant_freq = freq_low
        hue = frequency_to_hue(dominant_freq, freq_low, freq_high)

        # Build each row in this column using energy at the frequency
        # band that row corresponds to (top = high pitch, bottom = low)
        for row in range(height):
            pitch_bias = 1 - (row / height)
            row_freq = freq_low * (freq_high / freq_low) ** pitch_bias

            # Find energy near this row's target frequency
            idx = np.argmin(np.abs(freqs - row_freq))
            band = spectrum[max(0, idx - 2):idx + 3]
            energy = band.mean() if len(band) > 0 else 0

            # Combine local energy with overall loudness for brightness
            brightness = np.clip(energy / (spectrum.max() + 1e-9), 0, 1)
            brightness = 0.3 * loudness + 0.7 * brightness

            r, g, b = colorsys.hsv_to_rgb(hue, 0.75, brightness)
            img[row, col] = [int(r * 255), int(g * 255), int(b * 255)]

    out_img = Image.fromarray(img, "RGB")
    # Upscale with smoothing so it looks more like a painting, less like a grid
    out_img = out_img.resize((width * 6, height * 6), Image.BICUBIC)
    out_img.save(output_path)
    print(f"Saved: {output_path}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python sound_to_painting.py <wav_path> [output.png] [width] [height]")
        sys.exit(1)

    audio_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else "recovered.png"
    width = int(sys.argv[3]) if len(sys.argv) > 3 else 120
    height = int(sys.argv[4]) if len(sys.argv) > 4 else 40

    sound_to_painting(audio_path, output_path, width, height)